### ISSUE TITLE
CrystalDiskMark 7.0h does not read TargetPath or DriveLetter through DiskMark64.ini file

### ISSUE THREAD

**Issue by ossow** [hiyohiyo/CrystalDiskMark#10]
DIskamrk7.0h does not retrieve last location for testing performance. DiskMark ignore DrivePath/TargetPath and always set C: as default

https://user-images.githubusercontent.com/53398198/97053543-6c7d9280-1583-11eb-9850-ca96481f8be1.png

Prevoius revision (crystalDiskamrk 6) properly work with definied parameters DrivePath/TargetPath. 

May I ask for changing behaviour on CrystalDiskamrk7? It would be advisable for me I check some drives by editing ini file instead clicking data inside application.

**Comment by hiyohiyo** [comment]
I will fix this problem by CrystalDiskMark 8 RC2.

**Comment by ossow** [comment]
Thanks!
