### ISSUE TITLE
No Mix Test in CrystalDiskMark Shizuku Edition

### ISSUE THREAD

**Issue by fuchanghao** [hiyohiyo/CrystalDiskMark#11]
The Profile Menu in "Shizuku Edition" Don't have the [+Mix] option.

I checked the UWP Version and 8.0.0 RC Version which got the same problem.

I didn't find any docs that told me the Shizuku Edition is not the "Stand Edition+Themes", But some of the functions are not included.

**Comment by hiyohiyo** [comment]
Shizuku Edition does not support Mix Mode. 
Because theme image can not expand.

If you would like to use Mix Mode, please use Standard Edition.
