### ISSUE TITLE
Feature Request - Command Line Automation

### ISSUE THREAD

**Issue by SteveBrown2** [hiyohiyo/CrystalDiskMark#2]
Please add automation via command line.
Would like to set QD, xfer sizes, randomness, and other things from cmd line, have the test autostart and automatically write results to CSV, JSON, or other easily parsed format.

**Comment by joshwhieb** [comment]
@hiyohiyo  this would be great to have on the next CDM for large scale testing/reporting.

**Comment by hiyohiyo** [comment]
CrystalDiskMark is only GUI lapper of DiskSpd.
If you require an automation feature, please use DiskSpd directly.
